-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 16:22:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_categoria_R`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_categoria_R` (
  `categorias_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  INDEX `fk_producto_categoria_R_categorias_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_producto_categoria_R_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria_R_categorias`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_categoria_R_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idperfil`, `usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`id`, `perfil_idperfil`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `mydb`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sistema_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sistema_de_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden` (
  `idorden` INT NOT NULL,
  `fecha` DATE NULL,
  `Sistema_de_pago_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idorden`, `Sistema_de_pago_id`, `usuario_id`),
  INDEX `fk_orden_Sistema_de_pago1_idx` (`Sistema_de_pago_id` ASC) VISIBLE,
  INDEX `fk_orden_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_Sistema_de_pago1`
    FOREIGN KEY (`Sistema_de_pago_id`)
    REFERENCES `mydb`.`Sistema_de_pago` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orden_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_roducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_roducto` (
  `idorden_roducto` INT NOT NULL AUTO_INCREMENT,
  `productos_id` INT NOT NULL,
  `orden_idorden` INT NOT NULL,
  `orden_Sistema_de_pago_id` INT NOT NULL,
  `orden_usuario_id` INT NOT NULL,
  PRIMARY KEY (`idorden_roducto`, `productos_id`, `orden_idorden`, `orden_Sistema_de_pago_id`, `orden_usuario_id`),
  INDEX `fk_orden_roducto_productos1_idx` (`productos_id` ASC) VISIBLE,
  INDEX `fk_orden_roducto_orden1_idx` (`orden_idorden` ASC, `orden_Sistema_de_pago_id` ASC, `orden_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_roducto_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orden_roducto_orden1`
    FOREIGN KEY (`orden_idorden` , `orden_Sistema_de_pago_id` , `orden_usuario_id`)
    REFERENCES `mydb`.`orden` (`idorden` , `Sistema_de_pago_id` , `usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
